### ISSUE TITLE
errors running example 1

### ISSUE THREAD

**Issue by duhd1993** [wenbinyugroup/ivabs#39]
The error happens at https://github.itap.purdue.edu/wenbinyugroup/msg_design/blob/1841bdd0493506f039d578f8646ffdd7cd530db8/scripts/msgd/da/design_analysis.py#L347-L349

I believe it's because the data_proc_funcs cannot be imported successfully. You can manually append current path to sys.path. 
The search path is the path to the file of design_analysis.py which does not contain data_proc_funcs

**Comment by duhd1993** [comment]
It searches in e1 folder, but data_proc_funcs is not in e1 folder.
```
INFO     | 2022-06-09 14:12:59 | design_analysis.preprocess | import data_proc_funcs as user_mod
INFO     | 2022-06-09 14:12:59 | design_analysis.preprocess | from data_proc_funcs import materialId2Name
something wrong when importing module: data_proc_funcs
INFO     | 2022-06-09 14:12:59 | dakota.writeOutput | writing output files...
INFO     | 2022-06-09 14:12:59 | dakota.writeOutput | eval 147 failed
Traceback (most recent call last):
  File "/home/roger/a/du135/ivabs/scripts/msgd/ivabs.py", line 184, in runDakotaEval
    dda.analysis()
  File "/home/roger/a/du135/ivabs/scripts/msgd/da/dakota.py", line 605, in analysis
    design_analysis.run()
  File "/home/roger/a/du135/ivabs/scripts/msgd/da/cs.py", line 56, in run
    self.preprocess()
  File "/home/roger/a/du135/ivabs/scripts/msgd/da/design_analysis.py", line 361, in preprocess
    func_obj(self.data, self.sname, self.logger, *args, **kwargs)
UnboundLocalError: local variable 'func_obj' referenced before assignment
```
